// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('app.entry.js', [], ['lib1.sub', 'lib2.sub']);
goog.addDependency('lib1.js', ['lib1'], []);
goog.addDependency('lib11.js', ['lib1.sub'], ['lib1']);
goog.addDependency('lib2.js', ['lib2'], []);
goog.addDependency('lib21.js', ['lib2.sub'], ['lib2']);
